export const HTTPLOADING = 'http_loading';
export const SIDER = 'sider';
export const LOGIN = 'login';
export const USERINFO = 'user_info';
export const CANDOAS = 'can_do_advanced_search';
export const GET_MENUS_DATA = 'layout/menus-path-data';
export const GET_MANAGER_COUNTS='get_manager_counts';
export const UPDATE_IS_PAY ='update_isPay';
export const IS_FIRST ='is_first';
